version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://maxillaris_owner:npg_iKyRgLpzuN14@ep-odd-union-a54t86ip.us-east-2.aws.neon.tech/maxillaris?sslmode=require
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=maxillaris
      - PGHOST=db
      - PGPORT=5432
      - NODE_ENV=production
      - GRPC_PORT=50051
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maxillaris
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
